import type { CyclePhase } from '@/types/app';

export const SYMPTOM_TIPS: Record<string, string> = {
  cramps:              'A heating pad and gentle movement like walking or yoga can ease this.',
  bloating:            'Warm herbal teas and lighter meals tend to help. Avoid excess salt today.',
  headache:            'Stay well hydrated and try to reduce screen time if you can.',
  backache:            'Gentle stretching and heat on your lower back can bring real relief.',
  'breast tenderness': 'A well-fitting, supportive bra and reducing caffeine can help.',
  acne:                'Your skin is more reactive right now, so keep your routine simple and gentle.',
  'mood swings':       'Your nervous system is working hard. Reducing stimulation where possible helps.',
  fatigue:             'Even 10 minutes of rest or a short nap makes a meaningful difference today.',
  nausea:              'Small, frequent meals and ginger tea can settle this.',
  'food cravings':     'Cravings signal what your body needs, so lean into nourishing versions.',
  insomnia:            'Reduce screens an hour before bed and keep your room cool.',
  spotting:            'Spotting can be normal mid-cycle or at the end of a period. Track it.',
  discharge:           'Changes in discharge through your cycle are normal. It can help to note the pattern.',
  'hot flashes':       'Breathable fabrics and a cool drink nearby can make these more manageable.',
  'brain fog':         'Short focused sessions with breaks outperform long stretches when fog hits.',
};

export const PHASE_INSIGHT_TIPS: Record<CyclePhase, string[]> = {
  period: [
    'Your body is doing real work right now. Warmth, rest, and iron-rich foods help.',
    'This is a good time to slow down and let your body lead the pace.',
    'Gentle movement like walking or stretching tends to ease discomfort more than staying still.',
    'A warm drink and a few quiet minutes can do more than you\'d think today.',
    'Iron-rich foods like lentils and leafy greens help replenish what your body is using.',
    'If you\'re tired, that\'s your body asking for rest, not a flaw to push through.',
    'Heat on your lower belly genuinely eases cramps. It comforts and it works.',
    'Hydration helps with bloating and fatigue, so keep water close today.',
  ],
  follicular: [
    'Your focus and memory tend to sharpen in this phase, a great time to tackle hard things.',
    'New projects and plans started now have a natural momentum behind them.',
    'Your body is building energy reserves. Protein and leafy greens support that.',
    'Estrogen is climbing, so your mood and motivation often lift along with it.',
    'This is a natural window for planning and brave first steps.',
    'Your body responds well to movement now, so a workout may feel especially good.',
    'Fermented foods and greens support the fresh energy your body is building.',
    'Learning sticks more easily in this phase, so a lovely time to start something new.',
  ],
  ovulation: [
    'Your social energy is near its peak, and high-stakes conversations and creative bursts come more easily now.',
    'This is one of the best windows in your cycle for physical performance.',
    'Your skin and hair often look their best around ovulation, so enjoy it.',
    'Your words tend to flow more easily right now, so have that conversation.',
    'Staying hydrated matters more today, since your body is running at full capacity.',
    'Antioxidant-rich foods like berries and citrus support you through this window.',
    'You may feel more outgoing than usual, and that\'s worth leaning into.',
    'Energy peaks now, so it\'s a lovely time for something that asks a lot of you.',
  ],
  luteal: [
    'Your intuition tends to be sharper now. Trust what you notice.',
    'This phase can amplify stress, so reducing your load where possible is genuinely useful, not a luxury.',
    'Magnesium-rich foods like dark chocolate and leafy greens can ease luteal symptoms.',
    'Cravings here are real, so reach for satisfying, steady foods rather than fighting them.',
    'Complex carbs like oats and sweet potato help keep your mood and energy even.',
    'If you feel more sensitive, that\'s hormonal, not a weakness in you.',
    'Gentle movement and earlier nights pay off noticeably in this phase.',
    'Lightening your load now is genuinely useful, not indulgent.',
  ],
};
